#!/bin/bash
# Preflight an .xcarchive BEFORE uploading to App Store Connect.
#
# WHY THIS EXISTS
# Every check below corresponds to a real defect that shipped, or nearly
# shipped, from this project — each one silently, because the archive built
# fine and xcodebuild reported success:
#
#   2026-08-13  App shipped with NO CFBundleIcons: Assets.xcassets wasn't in
#               project.yml's source list, so actool never ran. It survived a
#               while only because stale PNGs sat in DerivedData.
#   2026-08-13  Release plist carried NSAllowsArbitraryLoads. The Debug/Release
#               ATS split lived in project.pbxproj, which is gitignored AND
#               regenerated by xcodegen, so every `xcodegen generate` restored
#               cleartext loads to the shipping build.
#   2026-08-14  CFBundleVersion was hardcoded to "1" by xcodegen, so bumping
#               CURRENT_PROJECT_VERSION had no effect on the uploaded build.
#   2026-08-14  ITSAppUsesNonExemptEncryption went missing, which holds a build
#               for manual export-compliance answers instead of distributing.
#   2026-08-14  The 1024 App Store icon had an ALPHA CHANNEL. Apple rejects
#               that ("can't be transparent nor contain an alpha channel") —
#               but only DURING PROCESSING, by email, so three builds sat in
#               "Processing" for a day with no API-visible error. The device
#               icons are flattened by actool, so the built app looked fine;
#               only the source .png in the appiconset carried the alpha.
#   2026-08-14  No UISupportedInterfaceOrientations — App Store Connect
#               REJECTED the upload (error 90474). INFOPLIST_KEY_* build
#               settings are ignored while GENERATE_INFOPLIST_FILE=NO.
#
# The common thread: settings that live in project.pbxproj do not survive
# `xcodegen generate`. Anything that must ship has to be in project.yml.
#
# Usage:  ./preflight-archive.sh <path-to.xcarchive> [expected-build-number]
# Exits non-zero on any failure — wire it in front of every upload.

set -uo pipefail
ARCHIVE="${1:-}"
EXPECTED_BUILD="${2:-}"
[ -d "$ARCHIVE" ] || { echo "✗ usage: ./preflight-archive.sh <path.xcarchive> [build#]"; exit 1; }

APP="$ARCHIVE/Products/Applications/Tbra.app"
PLIST="$APP/Info.plist"
[ -f "$PLIST" ] || { echo "✗ no Info.plist at $PLIST"; exit 1; }
pb() { /usr/libexec/PlistBuddy -c "Print :$1" "$2" 2>/dev/null; }

FAIL=0
ok()   { echo "  ✓ $1"; }
bad()  { echo "  ✗ $1"; FAIL=1; }

echo "── Preflight: $(basename "$ARCHIVE")"

# 1. App icon — the recurring one.
ICONNAME=$(pb "CFBundleIcons:CFBundlePrimaryIcon:CFBundleIconName" "$PLIST")
[ -n "$ICONNAME" ] && ok "CFBundleIconName = $ICONNAME" || bad "CFBundleIconName MISSING — actool didn't run (is Assets.xcassets in project.yml sources?)"

ICONFILE=$(ls "$APP"/AppIcon*.png 2>/dev/null | head -1)
if [ -n "$ICONFILE" ]; then
  BYTES=$(stat -f%z "$ICONFILE")
  DIM=$(sips -g pixelWidth "$ICONFILE" 2>/dev/null | tail -1 | tr -d ' ')
  if [ "$BYTES" -gt 2000 ]; then ok "icon $(basename "$ICONFILE") ${DIM} (${BYTES} bytes)"
  else bad "icon $(basename "$ICONFILE") is only ${BYTES} bytes — looks like a placeholder"; fi
else
  bad "NO AppIcon*.png in the bundle"
fi

if [ -f "$APP/Assets.car" ]; then
  if xcrun assetutil --info "$APP/Assets.car" 2>/dev/null | grep -q "AppIcon"; then
    ok "Assets.car contains AppIcon"
  else
    bad "Assets.car has no AppIcon rendition"
  fi
else
  bad "no Assets.car — the asset catalog was never compiled"
fi

# 1b. Source icon alpha — the reason builds 8-10 stalled in Processing.
#     actool strips alpha from the device icons, so checking only the built
#     bundle misses this entirely; the marketing icon inside Assets.car keeps
#     whatever the source .png had.
ICONSET="$(dirname "$0")/Assets.xcassets/AppIcon.appiconset"
if [ -d "$ICONSET" ]; then
  for SRC in "$ICONSET"/*.png; do
    [ -f "$SRC" ] || continue
    if sips -g hasAlpha "$SRC" 2>/dev/null | grep -q "hasAlpha: yes"; then
      bad "$(basename "$SRC") HAS AN ALPHA CHANNEL — Apple rejects the App Store icon during processing"
    else
      ok "$(basename "$SRC") has no alpha"
    fi
  done
fi

# 1c. Deployment target must NOT exceed the SDK it was built against.
#     `minos 27.0 / sdk 26.5` is unprocessable: App Store Connect leaves the
#     build in "Processing" forever, with no rejection and no email. This
#     stalled builds 8-13 (2026-08-14/15) and looked like a missing-icon
#     problem, because ASC shows a placeholder icon for anything that hasn't
#     finished processing.
MINOS=$(xcrun vtool -show-build-version "$APP/Tbra" 2>/dev/null | awk '/minos/{print $2}')
SDKV=$(xcrun vtool -show-build-version "$APP/Tbra" 2>/dev/null | awk '/sdk/{print $2}')
if [ -n "$MINOS" ] && [ -n "$SDKV" ]; then
  LOWEST=$(printf '%s\n%s\n' "$MINOS" "$SDKV" | sort -V | head -1)
  if [ "$LOWEST" = "$SDKV" ] && [ "$MINOS" != "$SDKV" ]; then
    bad "deployment target ($MINOS) is ABOVE the SDK ($SDKV) — ASC will never finish processing this"
  else
    ok "deployment target $MINOS <= SDK $SDKV"
  fi
fi

# 2. ATS must NOT be in a shipping build.
if pb "NSAppTransportSecurity" "$PLIST" >/dev/null 2>&1; then
  bad "NSAppTransportSecurity present — Release must NOT allow arbitrary loads"
else
  ok "no NSAppTransportSecurity (Release is clean)"
fi

# 3. Export compliance.
ENC=$(pb "ITSAppUsesNonExemptEncryption" "$PLIST")
[ -n "$ENC" ] && ok "ITSAppUsesNonExemptEncryption = $ENC" || bad "ITSAppUsesNonExemptEncryption MISSING — build will stall awaiting compliance answers"

# 4. Orientations (App Store Connect error 90474).
if pb "UISupportedInterfaceOrientations" "$PLIST" >/dev/null 2>&1; then
  ok "UISupportedInterfaceOrientations present"
else
  bad "UISupportedInterfaceOrientations MISSING — ASC rejects with error 90474"
fi

# 5. Version, and the extension must match it.
VER=$(pb "CFBundleShortVersionString" "$PLIST"); BUILD=$(pb "CFBundleVersion" "$PLIST")
ok "version $VER ($BUILD)"
if [ -n "$EXPECTED_BUILD" ] && [ "$BUILD" != "$EXPECTED_BUILD" ]; then
  bad "expected build $EXPECTED_BUILD but bundle says $BUILD"
fi
case "$BUILD" in *'$'*) bad "CFBundleVersion is an unexpanded variable: $BUILD";; esac

for EXT in "$APP"/PlugIns/*.appex; do
  [ -d "$EXT" ] || continue
  EB=$(pb "CFBundleVersion" "$EXT/Info.plist")
  if [ "$EB" = "$BUILD" ]; then ok "$(basename "$EXT") version matches ($EB)"
  else bad "$(basename "$EXT") is build $EB but the app is $BUILD — upload validation will reject"; fi
done

# 6. No dev endpoints baked into a shipping binary.
if strings "$APP/Tbra" 2>/dev/null | grep -qE "100\.84\.95\.103|localhost:3000"; then
  bad "binary contains a DEV endpoint (tailnet IP or localhost) — this is a Debug build"
else
  ok "no dev endpoints in the binary"
fi

echo
if [ "$FAIL" -eq 0 ]; then echo "PREFLIGHT PASSED — safe to upload"; else echo "PREFLIGHT FAILED — do not upload"; fi
exit $FAIL
